version: '3.7'
services:
  billetterie_postgres:
    extends:
      file: ../compose/docker-compose-base.yml
      service: billetterie_postgres
    env_file: .env
    networks:
      - backend-billeterie

  billetterie_redis:
    extends:
      file: ../compose/docker-compose-base.yml
      service: billetterie_redis
    networks:
      - backend-billeterie

  billetterie_django:
    extends:
      file: ../compose/docker-compose-base.yml
      service: billetterie_django
    command: "bash /DjangoFiles/launch_prod.sh"
    env_file: .env
    depends_on:
      - billetterie_postgres
    links:
      - billetterie_postgres:billetterie_postgres
      - billetterie_redis:redis
    networks:
      - frontend
      - backend-billeterie

  billetterie_celery:
    extends:
      file: ../compose/docker-compose-base.yml
      service: billetterie_celery
    command: "bash /DjangoFiles/launch_celery.sh"
    env_file: .env
    depends_on:
      - billetterie_django
    links:
      - billetterie_postgres:billetterie_postgres
      - billetterie_redis:redis
    networks:
#      - frontend
      - backend-billeterie

  billetterie_nginx:
    image : tibillet/front:latest
    env_file: .env
    depends_on:
      - billetterie_django
    links:
      - billetterie_django:billetterie_django
    networks:
      - frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../../DjangoFiles/www:/DjangoFiles/www
      - ../../DjangoFiles/logs:/DjangoFiles/logs
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.billetterie_nginx_prod.tls.certresolver=letsencrypt
      - traefik.http.routers.billetterie_nginx_prod.rule=HostRegexp(`{sub:[a-zA-Z0-9-]+}.${DOMAIN}`) || Host(`${DOMAIN}`)
      - traefik.http.routers.billetterie_nginx_prod.entrypoints=websecure

#  billetterie_daphne:
#    extends:
#      file: ../compose/docker-compose-base.yml
#      service: billetterie_celery
#    env_file: .env
#    container_name: billetterie_daphne
#    hostname: billetterie_daphne
#    depends_on:
#      - billetterie_django
#      - billetterie_postgres
#      - billetterie_redis
#    links:
#      - billetterie_postgres:billetterie_postgres
#      - billetterie_redis:redis
#    ports:
#      - 7999:7999
#    networks:
#      - frontend
#      - backend-billeterie
#    command: "bash /DjangoFiles/launch_ws.sh"

networks:
  frontend:
    external: true
  backend-billeterie:
    name: "backend-billeterie"

