version: '3'
services:
  Odoo_postgres:
    image: postgres:13
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - backend_odoo

    deploy:
      resources:
          limits:
            cpus: 2
            memory: 512M


  Odoo_web:
    image: odoo:15
    depends_on:
      - Odoo_postgres
    environment:
    - HOST=Odoo_postgres
    - USER=${POSTGRES_USER}
    - PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - frontend
      - backend_odoo
    volumes:
      - ./addons:/mnt/extra-addons
    deploy:
      resources:
          limits:
            cpus: 2
            memory: 512M
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend

      - traefik.http.services.Odoo3Peaks_web.loadbalancer.server.port=8069
      - traefik.http.routers.Odoo3Peaks_web.tls.certresolver=myresolver
      - traefik.http.routers.Odoo3Peaks_web.rule=Host(`${DOMAIN}`)

networks:
  frontend:
    external: true
  backend_odoo:
    name: "backend_odoo"
